### ISSUE TITLE
Instant Reload Addon Version Requirement Discrepancy

### ISSUE THREAD

**Issue by sappho7124** [getflywheel/local-addon-instant-reload#22]
I am using LocalWP for my WordPress development and attempted to install the Instant Reload addon. Upon installation, I was prompted with a requirement for LocalWP version 8, however, the latest available version on the official website is 7.2.1.

As far as i know Instant Reload addon was released for version 6 of LocalWP. Is there a possible version requirement mistake, or is there an update coming to align with the version 8 requirement shown in the addon?

I am currently on Windows 10 and the automatic update feature in LocalWP is not showing any available updates past version 7.2.1.

**Comment by alitwelve** [comment]
Same problem for me

**Comment by VincentvdRee** [comment]
Same issue here on a MacBook Pro running Ventura 13.5

**Comment by gitwinst** [comment]
Same issue, running macOS 10.15.7.

**Comment by sgloeggl** [comment]
Same issue here running macOS 13.5.2

**Comment by ali-han** [comment]
I think the Local auto-updater is not working correctly...

![image](https://github.com/getflywheel/local-addon-instant-reload/assets/42784461/ad263814-2cd3-450d-9567-31b24328c406)

Then I downloaded and installed v8.0 manually to fix the problem.
https://localwp.com/releases/

Now the instant reload addon working for me! 🥇

**Comment by sappho7124** [comment]
> I think the Local auto-updater is not working correctly...
> 
> ![image](https://user-images.githubusercontent.com/42784461/274322780-ad263814-2cd3-450d-9567-31b24328c406.png)
> 
> Then I downloaded and installed v8.0 manually to fix the problem. https://localwp.com/releases/
> 
> Now the instant reload addon working for me! 🥇

How did you update local to 8.0? the last release on the website seems to be 7.2.1

![localpng](https://github.com/getflywheel/local-addon-instant-reload/assets/38844048/c0d16a9f-7ca3-4138-860e-41fa497899bb)
